/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6575_NP. Copyright MediaTek Inc. (C) 2013.
 * Sun Aug 24 21:16:39 2014
 * Do Not Modify the File.
 */



#include "pmic_drv.h"



//For PMIC driver use


